# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries_code', models.CharField(max_length=20)),
                ('countries_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=20)),
                ('foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.countries')),
            ],
        ),
    ]
